version: '3.8'

services:
  face-verification:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    container_name: face-verification
    volumes:
      - ../../dataset:/app/dataset:ro
      - ../../models:/app/models
      - ../../logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true